name: Update Project Metadata

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  update-metadata:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check if new-project.json is modified
        id: check-template
        run: |
          TEMPLATE_CONTENT='{
            "name": "",
            "url": "https://github.com/username/project",
            "description": "",
            "category": "",
            "metadata": []
          }'

          # Remove whitespace for comparison
          NORMALIZED_TEMPLATE=$(echo "$TEMPLATE_CONTENT" | jq -c .)
          NORMALIZED_FILE=$(cat src/lib/data/new-project.json | jq -c .)

          if [ "$NORMALIZED_TEMPLATE" == "$NORMALIZED_FILE" ]; then
            echo "Template is unchanged, skipping metadata update"
            echo "unchanged=true" >> $GITHUB_OUTPUT
          else
            echo "Template has been modified, proceeding with update"
            echo "unchanged=false" >> $GITHUB_OUTPUT
          fi

      - name: Process new project
        if: steps.check-template.outputs.unchanged != 'true'
        run: pnpm tsx scripts/parse-template.ts

      - name: Update project metadata
        if: steps.check-template.outputs.unchanged != 'true'
        run: pnpm tsx scripts/update-metadata.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate README tables
        if: steps.check-template.outputs.unchanged != 'true'
        run: pnpm tsx scripts/generate-readme-tables.ts

      - name: Commit changes if any
        if: steps.check-template.outputs.unchanged != 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/lib/data/projects.json README.md src/lib/data/new-project.json
          git diff --staged --quiet || git commit -m "Update project metadata and README"
          git push
